# Generated by Django 3.2.15 on 2022-10-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phoneNo', models.IntegerField()),
                ('yourArea', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=100)),
            ],
        ),
    ]
