# Generated by Django 3.2.15 on 2022-10-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='firstName',
            new_name='first_Name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='lastName',
            new_name='last_Name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='phoneNo',
            new_name='phone_No',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='yourArea',
            new_name='your_Area',
        ),
    ]
