# Generated by Django 3.2.15 on 2022-10-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_childdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdetail',
            name='vaccine',
            field=models.CharField(choices=[('1', 'Vaccin1'), ('2', 'Vaccine2')], max_length=30),
        ),
    ]
