# Generated by Django 3.2.15 on 2022-11-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='news',
            name='about',
            field=models.CharField(max_length=50),
        ),
    ]
