# Generated by Django 3.2.15 on 2022-11-01 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_auto_20221101_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='Description',
            new_name='description',
        ),
    ]
